db: 
  #build: postgresql
  image: galacticfog.artifactoryonline.com/gestalt-postgres:latest
  ports: 
    - "5432:5432"
zookeeper:
  image: wurstmeister/zookeeper
  ports: 
    - "2181:2181"
kafka:
  image: wurstmeister/kafka:0.8.2.1
  ports:
    - "9092:9092"
  links: 
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: PUBLIC_HOSTNAME
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
