db: 
  #build: postgresql
  image: galacticfog.artifactoryonline.com/centos7postgresql938:latest
  ports: 
    - "5432:5432"
  environment: 
    DB_USER: gfadmin
    DB_PASS: changeme4242
    DB_NAME: postgres
zookeeper:
  image: wurstmeister/zookeeper
  ports: 
    - "2181:2181"
kafka:
  image: wurstmeister/kafka:0.8.2.1
  ports:
    - "9092:9092"
  links: 
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: PUBLIC_HOSTNAME
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
ifDataLoad: 
  image: galacticfog.artifactoryonline.com/utilimage:latest
  links: 
    - db
  environment: 
    DB_USER: gfadmin
    DB_PASS: changeme4242
    DB_NAME: postgres
  volumes:
    - if-data-load/createUsersAndDBs.sh:/tmp/createUsersAndDBs.sh
    - if-data-load/gestaltsecurity.pgr:/tmp/gestaltsecurity.pgr
    - if-data-load/gestaltbilling.pgr:/tmp/gestaltbilling.pgr
    - if-data-load/meta.pgr:/tmp/meta.pgr
    - if-data-load/globals.sql:/tmp/globals.sql
  entrypoint: /tmp/createUsersAndDBs.sh
meta: 
  image: galacticfog.artifactoryonline.com/gestalt-config:latest
  links:
    - db
  ports: 
    - "14374:9000"
  environment: 
    GESTALT_META:       http://PUBLIC_HOSTNAME:14374
    GESTALT_ORG:        "com.galacticfog"
    GESTALT_ID:         "gestalt-config"
    GESTALT_VERSION:    "1.0"
    GESTALT_ENV:        "appliance; DEV"
    GESTALT_NODE_ID:    "0"                                                                                                                
    GESTALT_SECRET:     "secret"                                                                                                           
    DATABASE_HOSTNAME:   db
    DATABASE_PORT:       5432
    DATABASE_USERNAME:   gestaltdev
    DATABASE_PASSWORD:   M8keitw0rk
    DATABASE_NAME:       meta
    DATABASE_TIMEOUT_MS: 5000
ifConfigTask:
  image: galacticfog.artifactoryonline.com/utilimage:latest
  links: 
    - meta
  environment:
    BLUEPRINT_NAME: gestalt-base-infrastructure
  volumes:
    - if-config-task/deploy-blueprint-set-config.sh:/tmp/deploy-blueprint-set-config.sh
    - env/security.env:/tmp/security.env
    - env/billing.env:/tmp/billing.env
    - env/launcher.env:/tmp/launcher.env
  entrypoint: /tmp/deploy-blueprint-set-config.sh
security: 
  image: galacticfog.artifactoryonline.com/gestalt-security:latest
  environment: 
    - env/security.env
  ports: 
    - "9455:9000"
billing:
  image: galacticfog.artifactoryonline.com/gestalt-billing:latest
  extends: 
    file: meta.yml
    service: metaconsumer
  environment: 
    - env/billing.env
  ports: 
    - "6111:9000"
#launcher: 
#  image: galacticfog.artifactoryonline.com/gestalt-launcher:latest
#  extends: 
#    file: meta.yml
#    service: metaconsumer
#  environment: 
#    - env/launcher.env
#  links: 
#    - db
#    - security
#  expose: 
#    - "443:9000"
