db: 
  #build: postgresql
  image: centos/postgresql
  ports: 
    - "5432:5432"
  environment: 
    DB_USER: gfadmin
    DB_PASS: changeme4242
    DB_NAME: postgres
zookeeper:
  image: wurstmeister/zookeeper
  ports: 
    - "2181:2181"
kafka:
  image: wurstmeister/kafka:0.8.2.1
  ports:
    - "9092:9092"
  links: 
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: PUBLIC_HOSTNAME
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
meta: 
  image: galacticfog.artifactoryonline.com/gestalt-config:latest
  links:
    - db
  ports: 
    - "14374:9000"
  environment: 
    DATABASE_HOSTNAME:   db
    DATABASE_PORT:       5432
    DATABASE_USERNAME:   username
    DATABASE_PASSWORD:   password
    DATABASE_NAME:       meta
    DATABASE_TIMEOUT_MS: 5000
ifConfigTask:
  image: galacticfog.artifactoryonline.com/utilimage:latest
  links: 
    - meta
  environment:
    BLUEPRINT_NAME: gestalt-base-infrastructure
  volumes:
    - if-config-task/example_deployment.json:/tmp/example_deployment.json
    - if-config-task/example_blueprints.json:/tmp/example_blueprints.json
    - if-config-task/deploy-blueprint-set-config.sh:/tmp/deploy-blueprint-set-config.sh
    - env/security.env:/tmp/security.env
    - env/billing.env:/tmp/billing.env
    - env/dns.env:/tmp/dns.env
    - env/launcher.env:/tmp/launcher.env
  entrypoint: /tmp/deploy-blueprint-set-config.sh
security: 
  image: galacticfog.artifactoryonline.com/gestalt-security:latest
  extends: 
    file: meta.yml
    service: metaconsumer
  environment: 
    - env/security.env
    - env/ssl.env
  ports: 
    - "9455:9000"
#billing:
#  image: galacticfog.artifactoryonline.com/gestalt-billing:latest
#  extends: 
#    file: meta.yml
#    service: metaconsumer
#  environment: 
#    - env/billing.env
#    - env/ssl.env
#  ports: 
#    - "6111:9000"
#dns:
#  image: galacticfog.artifactoryonline.com/gestalt-dns:latest
#  extends: 
#    file: meta.yml
#    service: metaconsumer
#  environment: 
#    - env/dns.env
#  expose: 
#    - "8053:9000"
launcher: 
  image: galacticfog.artifactoryonline.com/gestalt-launcher:latest
  extends: 
    file: meta.yml
    service: metaconsumer
  environment: 
    - env/launcher.env
    - env/ssl.env
  links: 
    - db
    - security
  expose: 
    - "443:9000"
