db: 
  #build: postgresql
  image: galacticfog.artifactoryonline.com/gestalt-postgres:latest
  ports: 
    - "5432:5432"
zookeeper:
  image: wurstmeister/zookeeper
  ports: 
    - "2181:2181"
kafka:
  image: wurstmeister/kafka:0.8.2.1
  ports:
    - "9092:9092"
  links: 
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: PUBLIC_HOSTNAME
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
meta: 
  image: galacticfog.artifactoryonline.com/gestalt-config:latest
  links:
    - db
  ports: 
    - "14374:9000"
  environment: 
    DATABASE_HOSTNAME:   db
    DATABASE_PORT:       5432
    DATABASE_USERNAME:   username
    DATABASE_PASSWORD:   password
    DATABASE_NAME:       meta
    DATABASE_TIMEOUT_MS: 5000
security: 
  image: galacticfog.artifactoryonline.com/gestalt-security:latest
  extends: 
    file: meta.yml
    service: metaconsumer
  environment: 
    - ./security.env
    - ./ssl.env
  ports: 
    - "9455:9000"
#billing:
#  image: galacticfog.artifactoryonline.com/gestalt-billing:latest
#  extends: 
#    file: meta.yml
#    service: metaconsumer
#  environment: 
#    - ./billing.env
#    - ./ssl.env
#  ports: 
#    - "6111:9000"
#dns:
#  image: galacticfog.artifactoryonline.com/gestalt-dns:latest
#  extends: 
#    file: meta.yml
#    service: metaconsumer
#  environment: 
#    - ./dns.env
#  expose: 
#    - "8053:9000"
launcher: 
  image: galacticfog.artifactoryonline.com/gestalt-launcher:latest
  extends: 
    file: meta.yml
    service: metaconsumer
  environment: 
    - ./launcher.env
    - ./ssl.env
  links: 
    - db
    - security
  expose: 
    - "443:9000"
